src/AppBundle/Entity/Review.php
<?php
namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\UniqueConstraint;

/**
 * @ORM\Entity
 * @ORM\Table(
 *     uniqueConstraints={
 *         @UniqueConstraint(
 *              name="unique_show_critic",
 *              columns={"show_id", "critic_id"}
 *         )
 *     }
 * )
 */
class Review
{
    const STATUS_NOT_STARTED = 0;
    const STATUS_IN_PROGRESS = 1;
    const STATUS_SUBMITTED_TO_MENTOR = 2;
    const STATUS_SUBMITTED_TO_ADMIN = 3;
    const STATUS_REJECTED = 4;
    const STATUS_APPROVED = 5;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\SchoolShow", inversedBy="reviews")
     */
    private $show;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Critic")
     */
    private $critic;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\ReviewRevision", mappedBy="review", cascade={"persist"})
     */
    private $revisions;

    /**
     * @ORM\Column(type="integer")
     */
    private $status;

    private $statuses = [
        self::STATUS_NOT_STARTED => 'Not yet started',
        self::STATUS_IN_PROGRESS => 'In Progress',
        self::STATUS_SUBMITTED_TO_MENTOR => 'Submitted to Mentor',
        self::STATUS_SUBMITTED_TO_ADMIN => 'Submitted to Admin',
        self::STATUS_REJECTED => 'Rejected',
        self::STATUS_APPROVED => 'Approved',
    ];

    function __construct(SchoolShow $show, Critic $critic)
    {

        $this->show = $show;
        $this->critic = $critic;
        $this->revisions = new ArrayCollection();
        $this->status = self::STATUS_NOT_STARTED;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getShow()
    {
        return $this->show;
    }

    /**
     * @param mixed $show
     */
    public function setShow($show)
    {
        $this->show = $show;
    }

    /**
     * @return mixed
     */
    public function getCritic()
    {
        return $this->critic;
    }

    /**
     * @param mixed $critic
     */
    public function setCritic($critic)
    {
        $this->critic = $critic;
    }

    /**
     * @return mixed
     */
    public function getRevisions()
    {
        $criteria = Criteria::create()
            ->orderBy(['created' => 'DESC'])
        ;
        return $this->revisions->matching($criteria);
    }

    public function getRevision(){
        //dump($this);exit;
        //return $this->getCurrentRevision();
        $currentRevision = $this->getCurrentRevision();
        $content = null;
        if($currentRevision instanceof ReviewRevision){
            $content = $currentRevision->getContent();
        }
        return $this->createNewRevision(
            $content
        );
    }

    public function setRevision(ReviewRevision $revision){
        if(!is_null($revision->getId())){
            // this is someone modifying an existing record.
            // we dont want that.  lets create a new revision
            $revision = $this->createNewRevision(
                $revision->getContent()
            );
        }
        // only if the content has changed
        $currentRevision = $this->getCurrentRevision();
        if($currentRevision instanceof ReviewRevision){
            if($revision->getContent() == $currentRevision->getContent()){
                return;
            }
        }
        $this->addRevision($revision);
    }

    public function addRevision(ReviewRevision $revision){
        if(!$this->revisions->contains($revision)){
            $this->revisions->add($revision);
            $revision->setReview($this);
        }
    }

    public function getCurrentRevision(){
        $criteria = Criteria::create()
            ->setMaxResults(1)
            ->orderBy(['revisionNo' => 'DESC'])
        ;
        $result = $this->revisions->matching($criteria);
        if(count($result) == 1){
            return $result[0];
        }
        return null;
    }

    public function createNewRevision($content = null){
        $currentRevision = $this->getCurrentRevision();
        $revisionNumber = 1;
        if($currentRevision instanceof ReviewRevision){
            $revisionNumber = $currentRevision->getRevisionNo() + 1;
        }
        $newRevision = new ReviewRevision();
        $newRevision->setContent($content);
        $newRevision->setRevisionNo($revisionNumber);
        $newRevision->setReview($this);
        return $newRevision;
    }

    /**
     * @return mixed
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function getStatusString(){
        if(array_key_exists($this->status,$this->statuses)){
            return $this->statuses[$this->status];
        }
        return 'Unknown';
    }

    /**
     * @param mixed $status
     */
    public function setStatus($status)
    {
        $this->status = $status;
    }


}

src/AppBundle/Entity/ReviewRevision.php
<?php
namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table
 */
class ReviewRevision
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Review", inversedBy="revisions")
     */
    private $review;

    /**
     * @ORM\Column(type="integer")
     */
    private $revisionNo;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created;

    function __construct(/*Review $review*/)
    {
        $this->revisionNo = 1;
        $this->created = new \DateTime();
        /*$this->review = $review;*/
    }

    function __toString()
    {
        return $this->content;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getReview()
    {
        return $this->review;
    }

    /**
     * @param mixed $review
     */
    public function setReview(Review $review)
    {
        $this->review = $review;
    }

    /**
     * @return mixed
     */
    public function getRevisionNo()
    {
        return $this->revisionNo;
    }

    /**
     * @param mixed $revisionNo
     */
    public function setRevisionNo($revisionNo)
    {
        $this->revisionNo = $revisionNo;
    }

    /**
     * @return mixed
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * @param mixed $content
     */
    public function setContent($content)
    {
        $this->content = $content;
    }

    /**
     * @return mixed
     */
    public function getCreated()
    {
        return $this->created;
    }

    public function getSize(){
        $content = strip_tags($this->content);
        if (function_exists('mb_strlen')) {
            return mb_strlen($content, '8bit');
        } else {
            return strlen($content);
        }
    }

}

src/AppBundle/Entity/User.php
<?php
namespace AppBundle\Entity;

use Doctrine\Common\Collections\Criteria;
use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table()
 */
class User extends BaseUser
{
    # Old Roles
    const ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN'; #equal to us admin
    const ROLE_ADMIN = 'ROLE_ADMIN'; # grouping of chair, pd, treasurer, manager
    const ROLE_SHOW_DIRECTOR = 'ROLE_SHOW_DIRECTOR';
    const ROLE_CHAPTER_BOARD = 'ROLE_CHAPTER_BOARD';
    const ROLE_CHAIRMAN = 'ROLE_CHAIRMAN';
    const ROLE_TREASURER = 'ROLE_TREASURER';
    const ROLE_STEERING_MEMBER = 'ROLE_STEERING_MEMBER';
    const ROLE_SCHOOL_ADVISER = 'ROLE_SCHOOL_ADVISER';
    const ROLE_SCHOOL_MENTOR = 'ROLE_SCHOOL_MENTOR';
    const ROLE_CRITIC = 'ROLE_CRITIC';
    const ROLE_LEAD_CRITIC = 'ROLE_LEAD_CRITIC';
    //const ROLE_PROCTOR = 'ROLE_PROCTOR';
    //const ROLE_TRUSTEE = 'ROLE_TRUSTEE';
    const ROLE_PROGRAM_MANAGER = 'ROLE_PROGRAM_MANAGER';
    const ROLE_VOTE_ADMIN = 'ROLE_VOTE_ADMIN';
    const ROLE_SCHOOL_ADVISOR = 'ROLE_SCHOOL_ADVISOR';

    # Identifying Roles
    const ROLE_SCHOOL_STAFF = 'ROLE_SCHOOL_STAFF';
    const ROLE_SCHOOL_STUDENT = 'ROLE_SCHOOL_STUDENT';

    # New Roles
    const ROLE_PROGRAM_DIRECTOR = 'ROLE_PROGRAM_DIRECTOR';

    # Grades
    const GRADE_FRESHMAN = 0;
    const GRADE_JUNIOR = 1;
    const GRADE_SOPHOMORE = 2;
    const GRADE_SENIOR = 3;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $namePrefix;

    /**
     * @ORM\Column(type="string")
     */
    protected $fName;

    /**
     * @ORM\Column(type="string")
     */
    protected $lName;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $nameSuffix;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Season")
     * @ORM\JoinColumn(name="season_logged_in_id", referencedColumnName="id", nullable=true)
     */
    protected $seasonLoggedIn;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\MappedSuperclass\SeasonalUser", mappedBy="user")
     */
    protected $activeSeasons;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $mobilePhone;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $homePhone;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $sfid;

    public function __construct(){
        parent::__construct();
        $this->password = uniqid();
    }

    public function __toString(){
        $name = trim($this->namePrefix.' '.$this->fName.' '.$this->lName.' '.$this->nameSuffix);
        if($name != ''){
            /*$position = $this->getCurrentPosition();
            if($position != ''){
                $name .= ' ('.$position.')';
            }*/
            return $name;
        }
        return parent::__toString(); // return username
    }

    /**
     * @return mixed
     */
    public function getFName()
    {
        return $this->fName;
    }

    /**
     * @param mixed $fName
     */
    public function setFName($fName)
    {
        $this->fName = $fName;
    }

    /**
     * @return mixed
     */
    public function getLName()
    {
        return $this->lName;
    }

    /**
     * @param mixed $lName
     */
    public function setLName($lName)
    {
        $this->lName = $lName;
    }

    public function setEmail($email)
    {
        if (filter_var($email, FILTER_VALIDATE_EMAIL)) {
            $aryEmailParts = explode('@', $email);
            if($aryEmailParts[0] != ''){
                parent::setUsername($aryEmailParts[0]);
            }
        }
        return parent::setEmail($email);
    }

    /**
     * @return mixed
     */
    public function getSeasonLoggedIn()
    {
        return $this->seasonLoggedIn;
    }

    /**
     * @param mixed $seasonLoggedIn
     */
    public function setSeasonLoggedIn(Season $seasonLoggedIn)
    {
        $this->seasonLoggedIn = $seasonLoggedIn;
    }

    public function isActiveInSeason(Season $season){
        $criteria = Criteria::create()->andWhere(Criteria::expr()->eq('season', $season));
        $activeUser = $this->activeSeasons->matching($criteria);
        if(count($activeUser) == 1){
            return $activeUser[0]->isActive();
        }
        return false;
    }

    public function getRoles()
    {
        if($this->seasonLoggedIn instanceof Season){
            $criteria = Criteria::create()->andWhere(Criteria::expr()->eq('season', $this->seasonLoggedIn));
            $activeUser = $this->activeSeasons->matching($criteria);
            if(count($activeUser) == 1){
                $this->roles = $activeUser[0]->getGroup()->getRoles();
            }
        }
        return parent::getRoles();
    }

    public function getCurrentPosition(){
        $position = $this->getActiveSeason();
        if($position instanceof Critic){
            return 'Critic';
        }elseif($position instanceof BoardMember){
            return "Board Member";
        }elseif($position instanceof SchoolStaff){
            return "School Administrator";
        }
        return "";
    }

    public function getActiveSeason(){
        $return = null;
        if($this->seasonLoggedIn instanceof Season){
            $criteria = Criteria::create()->andWhere(Criteria::expr()->eq('season', $this->seasonLoggedIn));
            $activeUser = $this->activeSeasons->matching($criteria);
            if(count($activeUser) == 1){
                $return = $activeUser[0];
            }
        }
        return $return;
    }

    /**
     * @return mixed
     */
    public function getActiveSeasons()
    {
        return $this->activeSeasons;
    }

    /**
     * @param mixed $activeSeasons
     */
    public function setActiveSeasons($activeSeasons)
    {
        $this->activeSeasons = $activeSeasons;
    }

    /**
     * @return mixed
     */
    public function getMobilePhone()
    {
        return $this->mobilePhone;
    }

    /**
     * @param mixed $mobileNumber
     */
    public function setMobilePhone($mobilePhone)
    {
        $this->mobilePhone = $mobilePhone;
    }

    /**
     * @return mixed
     */
    public function getHomePhone()
    {
        return $this->homePhone;
    }

    /**
     * @param mixed $homePhone
     */
    public function setHomePhone($homePhone)
    {
        $this->homePhone = $homePhone;
    }

    /**
     * @return mixed
     */
    public function getSfid()
    {
        return $this->sfid;
    }

    /**
     * @param mixed $sfid
     */
    public function setSfid($sfid)
    {
        $this->sfid = $sfid;
    }

    /**
     * @return mixed
     */
    public function getNamePrefix()
    {
        return $this->namePrefix;
    }

    /**
     * @param mixed $namePrefix
     */
    public function setNamePrefix($namePrefix)
    {
        $this->namePrefix = $namePrefix;
    }

    /**
     * @return mixed
     */
    public function getNameSuffix()
    {
        return $this->nameSuffix;
    }

    /**
     * @param mixed $nameSuffix
     */
    public function setNameSuffix($nameSuffix)
    {
        $this->nameSuffix = $nameSuffix;
    }

}

src/AppBundle/Form/CriticType.php
<?php
namespace AppBundle\Form;

use AppBundle\Entity\Critic;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CriticType extends SeasonalUserType
{

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Critic::class
        ]);
        parent::configureOptions($resolver);
    }

}

src/AppBundle/Resources/views/critic/assignments.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% block body %}
    <div class="border-bottom border-primary mb-3">
        <h1>Your Assignments</h1>
    </div>
    <table class="table table-sm table-hover">
        <tr class="bg-primary text-white">
            <th scope="col">Show</th>
            <th scope="col">Address</th>
            <th scope="col">Performance Date</th>
            {#<th scope="col">Dress Rehearsal Dates</th>#}
            <th scope="col">Actions</th>
        </tr>
        {% for show in shows %}
            <tr scope="row">
                <td>{{ show.name }}</td>
                <td>{{ show.address|nl2br }}</td>
                <td>
                    {{ show.selectedDate|date('F jS @ g:i a') }}
                    {#{% if is_granted('ROLE_CRITIC') %}
                        {{ dump(show.reviews(app.user.activeSeason)) }}
                    {% endif %}#}
                </td>
                {#<td>
                    <ul>
                        {% for date in show.dressRehearsalDates %}
                            <li>{{ date|date('F jS @ g:i a') }}</li>
                        {% endfor %}
                    </ul>
                </td>#}
                <td>
                    <a href="{{ path('critic_show_review', {"show":show.id}) }}" class="btn btn-outline-secondary">Review</a>
                    <a href="{{ path('decline_assignment', {"show":show.id}) }}" class="btn btn-outline-danger">Decline</a>
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

{% block stylesheets %}
    <style>
        ul {
            list-style: none;
            padding-left: 0;
        }
    </style>
{% endblock %}

src/AppBundle/Resources/views/critic/critic_volunteer.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% block body %}
    <div class="border-bottom border-primary mb-3">
        <h1>Volunteer for a Show</h1>
    </div>

    <ul class="nav nav-tabs pb-3" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Volunteer for a new show</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">My Volunteered Shows</a>
        </li>
    </ul>

    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
            <table class="table table-sm table-hover">
                <tr class="bg-primary text-white">
                    <th scope="col">Show</th>
                    <th scope="col">School</th>
                    <th scope="col">Address</th>
                    <th scope="col">Performance Date</th>
                    {#<th scope="col">Dress Rehearsal Dates</th>#}
                    <th scope="col">Actions</th>
                </tr>
                {% for show in shows %}
                    <tr scope="row">
                        <td>{{ show.name }}</td>
                        <td>{{ show.school }}</td>
                        <td>{{ show.address|nl2br }}</td>
                        <td>
                            {{ show.selectedDate|date('F jS @ g:i a') }}
                        </td>
                        {#<td>
                            <ul>
                                {% for date in show.dressRehearsalDates %}
                                    <li>{{ date|date('F jS @ g:i a') }}</li>
                                {% endfor %}
                            </ul>
                        </td>#}
                        <td>
                            <a href="{{ path('volunteer_for_show', {"show":show.id}) }}" class="btn btn-outline-secondary">Volunteer</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
            <table class="table table-sm table-hover">
                <tr class="bg-primary text-white">
                    <th scope="col">Show</th>
                    <th scope="col">School</th>
                    <th scope="col">Address</th>
                    <th scope="col">Performance Date</th>
                    {#<th scope="col">Dress Rehearsal Dates</th>#}
                    <th scope="col">Actions</th>
                </tr>
                {% for volunteer in volunteered %}
                    <tr scope="row">
                        <td>{{ volunteer.show.name }}</td>
                        <td>{{ volunteer.show.school }}</td>
                        <td>{{ volunteer.show.address|nl2br }}</td>
                        <td>
                            {{ volunteer.show.selectedDate|date('F jS @ g:i a') }}
                        </td>
                        {#<td>
                            <ul>
                                {% for date in show.dressRehearsalDates %}
                                    <li>{{ date|date('F jS @ g:i a') }}</li>
                                {% endfor %}
                            </ul>
                        </td>#}
                        <td>
                            <a href="{{ path('critic_show_review', {'show':volunteer.id}) }}" class="btn btn-outline-secondary">Write a Review</a>
                            <a href="{{ path('unvolunteer_for_show', {'show':volunteer.show.id}) }}" class="btn btn-outline-danger">Un-Volunteer</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

{% block stylesheets %}
    <style>
        ul {
            list-style: none;
            padding-left: 0;
        }
    </style>
{% endblock %}

src/AppBundle/Resources/views/critic/review.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% block body %}
    <div class="border-bottom border-primary mb-3">
        <h1>Review <em>{{ show }}</em></h1>
    </div>
    <p>Review Status: {{ review.statusString }}</p>
    <ul class="nav nav-tabs mb-3 border-bottom border-primary" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#currentVersion" role="tab" aria-controls="home" aria-selected="true">
                Current Revision
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#revisions" role="tab" aria-controls="profile" aria-selected="false">
                Revisions
            </a>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="currentVersion" role="tabpanel" aria-labelledby="home-tab">
            {% if is_granted(constant('AppBundle\\Security\\Voter\\ReviewVoter::CREATE_REVISION'), review) %}
                {{ form_start(form, {'attr':{'novalidate':'novalidate'}}) }}
                {{ form_widget(form.revision) }}
                {{ form_widget(form.submitReview) }}
                {{ form_widget(form.saveDraft) }}
                {{ form_end(form) }}
            {% else %}
                {{ review.currentRevision.content|raw }}
            {% endif %}
        </div>
        <div class="tab-pane fade" id="revisions" role="tabpanel" aria-labelledby="profile-tab">
            <table class="table table-hover table-sm">
                <tr class="bg-primary text-white">
                    <th>Revision number</th>
                    <th>Created</th>
                    <th>Size</th>
                    <th>Actions</th>
                </tr>
                {% for revision in review.revisions %}
                    <tr>
                        <td>
                            {{ revision.revisionNo }}
                            {% if loop.first %}
                                <i class="fa fa-star" style="color:gold;"></i>
                            {% endif %}
                        </td>
                        <td>{{ revision.created|date('Y-m-d H:i:s') }}</td>
                        <td>{{ revision.size }}</td>
                        <td>
                            <a href="#" class="btn btn-primary revisionModal" data-revision="{% spaceless %}{{ revision.content }}{% endspaceless %}">View</a>
                            {% if is_granted(constant('AppBundle\\Security\\Voter\\ReviewVoter::CREATE_REVISION'), review) %}
                                <a href="#" class="btn btn-outline-secondary">Revert</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}

            </table>
        </div>
    </div>


{% endblock %}

{% block javascripts %}
    <script src="{{ asset('bundles/app/js/tinymce/tinymce.min.js') }}"></script>
    <script src="{{ asset('bundles/app/js/bootbox.min.js') }}"></script>
    <script>
        tinymce.init({
            selector:'textarea',
            branding: false,
            plugins: "fullscreen",
            menubar: false,
            //toolbar: "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | fullscreen",
            toolbar: "undo redo | bold italic | bullist numlist | outdent indent | fullscreen",
            height : "480"
        });
        $(function () {
            $('.revisionModal').on('click', function(e){
                e.preventDefault();
                var html = $(this).data('revision');
                bootbox.alert({
                    message: html,
                    size: 'large',
                    className: 'custom-modal'
                });
            });
        });
    </script>
{% endblock %}

{% block stylesheets %}
    <style>
        .custom-modal .modal-dialog{
            max-width: 1300px;
        }
    </style>
{% endblock %}

src/AppBundle/Resources/views/critic/reviews_dashboard.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% block body %}
    <div class="border-bottom border-primary mb-3">
        <h1>Reviews</h1>
    </div>
    <table class="table table-hover table-sm">
        <tr class="bg-primary text-white">
            <th>Show</th>
            <th>Review Deadline</th>
            <th>Date</th>
            <th>Time</th>
            <th>Actions</th>
        </tr>
        {% for show in shows %}
            {% set review = show.reviews(app.user.activeSeason) %}
            {% if review is null or is_granted(constant('AppBundle\\Security\\Voter\\ReviewVoter::CREATE_REVISION'), review) %}
                <tr>
                    <td>{{ show }}</td>
                    <td>
                        {% if show.reviewDeadline is not null %}
                            {{ show.reviewDeadline|date('F jS @ g:i a') }}
                        {% endif %}
                    </td>
                    <td>{{ show.selectedDate|date('D, F jS Y') }}</td>
                    <td>{{ show.selectedDate|date('g:i a') }}</td>
                    <td>
                        <a href="{{ path('critic_show_review', {'show':show.id}) }}" class="btn btn-secondary">Review</a>
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
    </table>
{% endblock %}

{% block javascripts %}{% endblock %}

{% block stylesheets %}{% endblock %}

src/AppBundle/Resources/views/critic/send_email.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% block body %}
    <div class="border-bottom border-primary mb-3">
        <h1>
            Send an email
            {% if is_granted('ROLE_CRITIC') %}
                to lead critic
            {% endif %}
        </h1>
    </div>
    {{ form(form) }}
{% endblock %}

src/AppBundle/Resources/views/critic/submitted_reviews_dashboard.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% block body %}
    <div class="border-bottom border-primary mb-3">
        <h1>Submitted Reviews</h1>
    </div>
    <table class="table table-hover table-sm">
        <tr class="bg-primary text-white">
            <th>Show</th>
            <th>Status</th>
            <th>Last Revision Date</th>
            <th>Actions</th>
        </tr>
        {% for review in reviews %}
            <tr>
                <td>{{ review.show }}</td>
                <td>{{ review.statusString }}</td>
                <td>{{ review.currentRevision.created|date('Y-m-d H:i:s') }}</td>
                <td>
                    <a href="#" class="btn btn-outline-secondary view" data-content="{% spaceless %}{{ review.currentRevision.content }}{% endspaceless %}">View</a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('bundles/app/js/bootbox.min.js') }}"></script>
    <script>
        $(function () {
            $('.view').on('click', function(e){
                e.preventDefault();
                var html = $(this).data('content');
                bootbox.alert({
                    message: html,
                    size: 'large',
                    className: 'custom-modal'
                });
            });
        });
    </script>
{% endblock %}

{% block stylesheets %}
    <style>
        .custom-modal .modal-dialog{
            max-width: 1300px;
        }
    </style>
{% endblock %}